name: Push to main
on:
  push:
    branches:
      - main
      - support/implement-packaging

  workflow_dispatch:

jobs:
  lint-and-check:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies with Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version
          yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier check
        run: yarn pretty:fix --check

  build-image:
    name: Build Docker Image
    needs:
      - lint-and-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container image
        uses: docker/build-push-action@v6

  publish-release:
    name: Publish Release Package
    needs:
      - build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies with Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version
          yarn install --immutable

      - name: Build API
        run: yarn build:types && ls -la && ls -la ./dist

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn release --ci
